.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH PW3270 1 "JUNE 2012" pw3270 "User Manual"
.SH NAME
pw3270.conf \- configuration file for pw3270
.SH SYNOPSIS
This configuration file can be used to pre-customize some of pw3270's features.

The order of precedence while searching for this file is:
.IP "/etc/pw3270.conf"
System-wide configuration.

.IP "~/.config/pw3270.conf"
User-specific configuration.

.SH SECTIONS

The file follows a windows-style INI file format, with section name headers in square brackets, and parameters in the "name=value" syntax.

.IP "Section: view"

Contains configuration relative to the GUI elements.

.I toolbar.default
.RS 
Indicates whether the main toolbar is visible or not. 
.B Default: true.

.RE
.IP "Section: host"

Contains configuration relative to the hosts available for the user to connect to.

.I uri
.RS
Hostname or IP address, in the format hostname:port. Use s:hostname:port for SSL connections.
 
.RE

.SH AUTHORS
Perry Werneck <perry.werneck at gmail dot com>

Erico Mendonca <erico.mendonca at gmail dot com>

The official project page is located at http://www.softwarepublico.gov.br/dotlrn/clubs/pw3270 . 

.SH "SEE ALSO"
.BR pw3270 (1)

