#!/usr/bin/env bash

#!/bin/bash
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#
# Copyright (C) 2023 Perry Werneck <perry.werneck@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# References:
#
#   https://stackoverflow.com/questions/1596945/building-osx-app-bundle
#
APPNAME="pw3270"

APPDIR=${APPNAME}.app

rm -fr ${APPDIR}
mkdir -p ${APPDIR}
mkdir -p ${APPDIR}/Contents
mkdir -p ${APPDIR}/Contents/MacOS
mkdir -p ${APPDIR}/Contents/MacOS/lib
mkdir -p ${APPDIR}/Contents/MacOS/bin
mkdir -p ${APPDIR}/Contents/Resources


install_libraries() {

    # First copy the required libraries
    for path in $(otool -L ${1} | tail -n +2 | grep -v "/usr/lib/" | grep -v "/System" | cut -d\( -f1)
    do
        dpath="${APPDIR}/Contents/MacOS/lib/$(basename ${path})"
        
        echo "Copying ${path} to ${dpath}"
        cp "${path}" "${dpath}"
        if [ "$?" != "0" ]; then
            echo "Error copying ${path}"
            exit -1
        fi

        install_name_tool \
            -change \
                ${path} \
                @executable_path/lib/$(basename ${path}) \
                ${1}
    done

    # Resolve library dependencies
    again=1
    while [ "${again}" == "1" ]
    do
        again=0
        for libname in $(find ${APPDIR}/Contents/MacOS/lib -name "*.dylib")
        do
            echo "Checking ${libname}"
            for path in $(otool -L ${libname} | tail -n +2 | grep -v "@executable_path/" | grep -v "/System/" | grep -v "/usr/lib/" | cut -d\( -f1)
            do
                dpath="${APPDIR}/Contents/MacOS/lib/$(basename ${path})"

                if [ ! -e "${dpath}" ]; then
                    again=1
                    echo "Copying ${path} to ${dpath}"
                    cp "${path}" "${dpath}"
                    if [ "$?" != "0" ]; then
                        echo "Error copying ${path}"
                        exit -1
                    fi
                fi

                install_name_tool \
                    -change \
                        ${path} \
                        @executable_path/lib/$(basename ${path}) \
                        ${libname}

            done

        done
    done

}

cp .build/${APPNAME} ${APPDIR}/Contents/MacOS
if [ "$?" != "0" ]; then
    echo "Error copying ${APPNAME}"
    exit -1
fi

install_libraries ${APPDIR}/Contents/MacOS/${APPNAME}


find ${APPDIR}
