#!/usr/bin/env bash

#!/bin/bash
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#
# Copyright (C) 2023 Perry Werneck <perry.werneck@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# References:
#
#   https://stackoverflow.com/questions/1596945/building-osx-app-bundle
#
APPNAME="pw3270"

APPDIR=${PWD}/${APPNAME}.app

rm -fr ${APPDIR}
mkdir -p ${APPDIR}
mkdir -p ${APPDIR}/Contents
mkdir -p ${APPDIR}/Contents/MacOS
mkdir -p ${APPDIR}/Contents/MacOS/lib
mkdir -p ${APPDIR}/Contents/Resources
mkdir -p ${APPDIR}/Contents/Resources/plugins

install_libraries() {

    # Copy the required libraries
    for path in $(otool -L ${1} | tail -n +2 | grep -v "/usr/lib/" | grep -v "/System" | cut -d\( -f1)
    do
        dpath="${APPDIR}/Contents/MacOS/lib/$(basename ${path})"
        
        cp -v "${path}" "${dpath}"
        if [ "$?" != "0" ]; then
            echo "Error copying ${path}"
            exit -1
        fi

        install_name_tool \
            -change \
                ${path} \
                @executable_path/lib/$(basename ${path}) \
                ${1}
    done

    # Copy gdk pixbuf loaders
    GDK_PIXBUF_SRC=$(pkg-config --variable=gdk_pixbuf_binarydir gdk-pixbuf-2.0)
    GDK_PIXBUF_DIR=$(echo ${GDK_PIXBUF_SRC} | sed -e "s@$(pkg-config --variable=libdir gdk-pixbuf-2.0)@@g")

    mkdir -p "${APPDIR}/Contents/MacOS/lib/${GDK_PIXBUF_DIR}/loaders"
    for loader in $(find $(pkg-config --variable=gdk_pixbuf_binarydir gdk-pixbuf-2.0)/loaders -name "*.so")
    do
        cp -v "${loader}" "${APPDIR}/Contents/MacOS/lib/${GDK_PIXBUF_DIR}/loaders"
        if [ "$?" != "0" ]; then
            echo "Error copying ${loader}"
            exit -1
        fi
    done

    # Resolve library dependencies
    again=1
    while [ "${again}" == "1" ]
    do
        again=0
        for libname in $(find ${APPDIR}/Contents/MacOS/lib -name "*.dylib") $(find ${APPDIR}/Contents/MacOS/lib -name "*.so")
        do
            echo "Checking ${libname}"
            for path in $(otool -L ${libname} | tail -n +2 | grep -v "@executable_path/" | grep -v "/System/" | grep -v "/usr/lib/" | cut -d\( -f1)
            do
                dpath="${APPDIR}/Contents/MacOS/lib/$(basename ${path})"

                if [ ! -e "${dpath}" ]; then
                    again=1
                    cp -v "${path}" "${dpath}"
                    if [ "$?" != "0" ]; then
                        echo "Error copying ${path}"
                        exit -1
                    fi
                fi

                install_name_tool \
                    -change \
                        ${path} \
                        @executable_path/lib/$(basename ${path}) \
                        ${libname}

            done

        done

    done

}

install_schemas() {             

    mkdir -p ${APPDIR}/Resources/share/glib-2.0/schemas

    gtk_schemas="org.gtk.Settings.FileChooser.gschema.xml"
    glib_schemas="gschema.dtd"

    for schema in ${gtk_schemas}
    do
        filepath=$(pkg-config --variable=prefix gtk+-3.0)/share/glib-2.0/schemas/${schema}
        echo ${filepath}
        cp -v \
            ${filepath} \
            ${APPDIR}/Contents/Resources/glib-2.0/schemas
        if [ "$?" != "0" ]; then
            exit -1
        fi
    done

    for schema in ${glib_schemas}
    do
        filepath=$(pkg-config --variable=prefix glib-2.0)/share/glib-2.0/schemas/${schema}
        echo ${filepath}
        cp -v \
            ${filepath} \
            ${APPDIR}/Contents/Resources/glib-2.0/schemas
        if [ "$?" != "0" ]; then
            exit -1
        fi
    done

    glib-compile-schemas \
        --targetdir="${APPDIR}/Contents/Resources/glib-2.0/schemas" \
        "${APPDIR}/Contents/Resources/glib-2.0/schemas"

    if [ "$?" != "0" ]; then
        exit -1
    fi

}

install_locale() {
    base_libraries="lib3270 libv3270 glib-2.0 gtk+-3.0"
    for library in ${base_libraries}
    do
        cp -R -v \
            $(pkg-config --variable=prefix ${library})/share/locale/* \
            ${APPDIR}/Contents/Resources/locale
        if [ "$?" != "0" ]; then
            echo "Error copying locale for ${library}"
            exit -1
        fi
    done
}

build_package() {

    # Reconfigure & build
    rm -fr .build
    meson setup \
        --prefix=/ \
        --reconfigure \
        --wipe \
        --buildtype=debug \
        -D debug=true \
        .build
    if [ "$?" != "0" ]; then
        echo "Meson setup has failed"
        exit -1
    fi

    meson compile -C .build
    if [ "$?" != "0" ]; then
        echo "Meson compile has failed"
        exit -1
    fi

    DESTDIR=${APPDIR}/Contents/MacOS meson install -C .build
    if [ "$?" != "0" ]; then
        echo "Meson compile has failed"
        exit -1
    fi

    mv ${APPDIR}/Contents/MacOS/bin/* ${APPDIR}/Contents/MacOS
    if [ "$?" != "0" ]; then
        echo "Error moving bin/* to ${APPDIR}/Contents/MacOS"
        exit -1
    fi

    mv ${APPDIR}/Contents/MacOS/share/${APPNAME}/icons ${APPDIR}/Contents/Resources
    if [ "$?" != "0" ]; then
        echo "Error moving icons to ${APPDIR}/Contents/Resources"
        exit -1
    fi

    mv ${APPDIR}/Contents/MacOS/share/${APPNAME}/*.svg ${APPDIR}/Contents/Resources/icons
    if [ "$?" != "0" ]; then
        echo "Error moving icons to ${APPDIR}/Contents/Resources"
        exit -1
    fi

    mv ${APPDIR}/Contents/MacOS/share/${APPNAME}/* ${APPDIR}/Contents/Resources
    if [ "$?" != "0" ]; then
        echo "Error moving icons to ${APPDIR}/Contents/Resources"
        exit -1
    fi

    mv ${APPDIR}/Contents/MacOS/share/* ${APPDIR}/Contents/Resources
    if [ "$?" != "0" ]; then
        echo "Error moving icons to ${APPDIR}/Contents/Resources"
        exit -1
    fi

    rmdir ${APPDIR}/Contents/MacOS/bin ${APPDIR}/Contents/MacOS/share ${APPDIR}/Contents/Resources/plugins ${APPDIR}/Contents/Resources/${APPNAME}
    if [ "$?" != "0" ]; then
        echo "Error remmoving unused paths"
        exit -1
    fi

}

cp -v mac/info.plist ${APPDIR}/Contents
if [ "$?" != "0" ]; then
    echo "Error copying info.plist"
    exit -1
fi

build_package
install_libraries ${APPDIR}/Contents/MacOS/${APPNAME}
install_locale
install_schemas

find ${APPDIR}
