// This is the type library for libhllapi.dll

//
// References:
//
// http://support.microsoft.com/kb/189133
// http://msdn.microsoft.com/en-us/library/windows/desktop/aa367300(v=vs.85).aspx
//
[
      // Use GUIDGEN.EXE to create the UUID that uniquely identifies
      // this library on the user's system. NOTE: This must be done!!
      uuid(4CC73F7D-5C10-4313-8FFD-F01999A44656),

      // This helpstring defines how the library will appear in the
      // References dialog of VB.
      helpstring("PW3270 HLLAPI typelib"),

      // Assume standard English locale.
      lcid(0x0409),

      // Assign a version number to keep track of changes.
      version(5.0)
]

library HLLAPI
{

      // Now define the module that will "declare" your C functions.
      [
            helpstring("HLLAPI calls for pw3270"),

            version(5.0),

            // Give the name of your DLL here.
            dllname("libhllapi.dll")
      ]

      module hllApiFunctions
      {
            [
                  helpstring("Initialize pw3270´s instance."),
                  entry("hllapi_init")
            ]
            // The [in], [out], and [in, out] keywords tell the Automation
            // client which direction parameters need to be passed. Some
            // calls can be optimized if a function only needs a parameter
            // to be passed one-way.
            DWORD __stdcall hllapi_init( [in] LPSTR mode);


      } // End of Module

}; // End of Library
