#!/bin/bash

export HOST_CC=/usr/bin/gcc
export cache=win64.cache

OPT=$@

OFFICE=$(grep -c 'AC_ARG_ENABLE(\[office' configure.ac)

if [ "$OFFICE" != "0" ]; then
	OPT="$OPT --disable-office"
fi

if [ -d ~/win64/jdk ]; then
	export JDK_HOME=$(readlink -f ~/win64/jdk)
fi

if [ -d ~/win64/jre ]; then
	export JRE_HOME=$(readlink -f ~/win64/jre)
fi


./configure --cache-file=$cache \
			--host=x86_64-w64-mingw32 \
			--prefix=/usr/x86_64-w64-mingw32/sys-root/mingw \
			--libdir=/usr/x86_64-w64-mingw32/sys-root/mingw/lib \
			$OPT

status=$?

rm -f "$cache"
exit $status

